from core.tools.SingletonMeta import SingletonMeta

class KeysJson(metaclass=SingletonMeta):
    """description of class"""
    FreeCompany = "FreeCompany"
    Active = "Active"
    ActiveMemberCount = "ActiveMemberCount"
    Crest = "Crest"
    DC = "DC"
    Estate = "Estate"
    Greeting = "Greeting"
    Name = "Name"
    Plot = "Plot"
    Focus = "Focus"
    Icon = "Icon"
    Status = "Status"
    Formed = "Formed"
    GrandCompany = "GrandCompany"
    ID = "ID"
    ParseDate = "ParseDate"
    Rank = "Rank"
    Ranking = "Ranking"
    Monthly = "Monthly"
    Weekly = "Weekly"
    Recruitment = "Recruitment"
    Reputation = "Reputation"
    Progress = "Progress"
    Seeking = "Seeking"
    Server = "Server"
    Slogan = "Slogan"
    Tag = "Tag"